# Generated by Django 5.1.5 on 2025-02-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0006_rename_contact_number_member_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='user',
        ),
        migrations.AddField(
            model_name='member',
            name='name',
            field=models.CharField(default='Member', max_length=100),
        ),
    ]
