# Generated by Django 5.1.5 on 2025-02-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0008_alter_member_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('chairman', 'Chairman'), ('treasurer', 'Treasurer'), ('admin', 'Secretary'), ('tenant', 'Tenant'), ('flat_owner', 'Flat Owner')], max_length=50),
        ),
    ]
